### ISSUE TITLE
review use of string constants

### ISSUE THREAD

**Issue by GitMensch** [mridoni/gixsql#57]
Especially with `starts_with` there are multiple usages of "string constants".

Main issues:

* is the current use "correct" - related to casing? We do have a lot "all upper case" comparisons using this and for example in  `DbInterfacePGSQL::exec_params` we use both "all upper" and "all lower" https://github.com/mridoni/gixsql/blob/069249dee273f808b103b0f2d631c528c2880c30/runtime/libgixsql-pgsql/DbInterfacePGSQL.cpp#L381 (but in no place "mixed case")
* Shouldn't there be a "starts_with_ignore_case" which is called with a dynamic part and a constant, the later always being upper-case?
* Would it be reasonable to also allow \t delimiters instead of space?
* Shouldn't it be possible for the most common use case - the integration of "fixed" sql - to check for delete/update/... at preprocessor time including a flag and checking this, instead of checking for "delete" every time a (likely different) statement is executed?

Additional:
Should we gather all those constants in a single namespace, possibly as [string_view](https://en.cppreference.com/w/cpp/string/basic_string_view/operator%22%22sv)?
I've stumbled over this when stepping through the code, the line referenced above creates a std:string each time a plain string literal is used; and that's a lot to step through in libcstd++, starting with

```
#0  0x00007f61158a9480 in malloc () from /usr/lib64/libc.so.6
#1  0x00007f610e296d6c in operator new(unsigned long) () from /usr/lib64/libstdc++.so.6
#2  0x00007f61101b0660 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (...) at /usr/include/c++/8/bits/basic_string.tcc:219
#3  0x00007f610773500b in DbInterfacePGSQL::exec_params (...) at DbInterfacePGSQL.cpp:381
```

I _guess_ those std::strings are deleted upon return of `starts_with` or at least at the end of `DbInterfacePGSQL::exec_params`, but I don't know.

... and yes: I currently get a memory out of bound at exactly this place... (because there's a resource leak somewhere [most likely: else]).

**Comment by mridoni** [comment]
Thanks for pointing this out, I will look into it. 

P.S. For now I am advancing with the work on the standalone debugger in the IDE . I should be able to give a timeframe in a few days. I have starting working on implementing the WHENEVER handler, but I am also experiencing a surge in my day-job, so all of this is likely to proceed slower than usual.

**Comment by GitMensch** [comment]
Leaving a ping because of both possible performance and bug reasoning (the later may apply when SQL is used not in upper-case, which is not a case in my personal testing scenarios but likely in someones code).
